baseURL = 'https://funcionesquefuncionan.github.io/'
languageCode = 'en-us'
title = 'funciones que funcionan'
theme = 'm10c'

enableRobotsTXT = true

author = 'Peter Gassendi'

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"

[[params.social]]
  icon = "twitter"
  name = "Twitter"
  url = "https://twitter.com/petergassendi"

[[params.social]]
  icon = "mail"
  name = "Email"
  url = "mailto:pgassendi@gmail.com"

[[params.social]]
  icon = "rss"
  name = "RSS"
  url = "https://funcionesquefuncionan.github.io/index.xml"

